title: 'Purelog: for Writers'
email: mail@brennanbrown.ca
description: >-
  A responsive sidebar Jekyll theme using the Pure.css framework,  designed for
  writers and bloggers of all kinds.
baseurl: ''
url: ''
repository: brennanbrown/purelog
twitter: brennankbrown
github: brennanbrown
header_image: assets/profile.png
google_analytics: null
comments: true
disqus: purelog-jekyll
author: Brennan K. Brown
author_bio: "Hey there! \U0001F604 My name is Brennan, I'm a 25-year-old Métis web developer and  content strategist from Winnipeg, Manitoba and currently reside in Calgary,  Alberta. I've recently compeleted a Full Stack Developer Program at EvolveU,  and I'm looking to help those that need web development work done, or  searching for ideas and management for their next content project."
author_pic: 'https://brennanbrown.ca/img/avatar.png'
paginate: 4
paginate_path: '/:num/'
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
permalink: '/:title'
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      author: Brennan K. Brown
      avatar: assets/profile-sm.png
  - scope:
      path: ''
      type: notes
    values:
      layout: post
      content-type: notes
  - scope:
      path: ''
      type: journals
    values:
      layout: journal-entry
      content-type: journals
collections:
  pages:
    output: true
    permalink: '/:title'
  notes:
    output: true
    permalink: '/notes/:title'
  journals:
    output: true
    permalink: '/journals/:title'
exclude:
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
